create schema ramya;
 
CREATE TABLE ramya.IDENTITIES (
    IDENTITY_UID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    IDENTITY_DISPLAYNAME VARCHAR(255),
    IDENTITY_EMAIL VARCHAR(255),
    IDENTITY_BIRTHDATE DATE
)

ALTER TABLE ramya.IDENTITIES ADD CONSTRAINT IDENTIES_PK PRIMARY KEY (IDENTITY_UID); 

--DROP TABLE TOM.IDENTITIES;

select * from ramya.Identities; 
where IDENTITIES.IDENTITY_EMAIL = 'parameter';

-- parameter = "blabla" OR 1=1; DROP TABLE IDENTITIES; "